# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bolpy/proto/bol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bolpy/proto/bol.proto',
  package='bolproto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x62olpy/proto/bol.proto\x12\x08\x62olproto\")\n\x05Price\x12\r\n\x05price\x18\x01 \x01(\x02\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"j\n\x16PriceEvaluationRequest\x12%\n\x0c\x63urrentPrice\x18\x01 \x01(\x0b\x32\x0f.bolproto.Price\x12)\n\x10historicalPrices\x18\x02 \x03(\x0b\x32\x0f.bolproto.Price\")\n\x17PriceEvaluationResponse\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t2h\n\x0ePriceEvaluator\x12V\n\rEvaluatePrice\x12 .bolproto.PriceEvaluationRequest\x1a!.bolproto.PriceEvaluationResponse\"\x00\x62\x06proto3')
)




_PRICE = _descriptor.Descriptor(
  name='Price',
  full_name='bolproto.Price',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='bolproto.Price.price', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='bolproto.Price.timestamp', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=76,
)


_PRICEEVALUATIONREQUEST = _descriptor.Descriptor(
  name='PriceEvaluationRequest',
  full_name='bolproto.PriceEvaluationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currentPrice', full_name='bolproto.PriceEvaluationRequest.currentPrice', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='historicalPrices', full_name='bolproto.PriceEvaluationRequest.historicalPrices', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=184,
)


_PRICEEVALUATIONRESPONSE = _descriptor.Descriptor(
  name='PriceEvaluationResponse',
  full_name='bolproto.PriceEvaluationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='bolproto.PriceEvaluationResponse.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=227,
)

_PRICEEVALUATIONREQUEST.fields_by_name['currentPrice'].message_type = _PRICE
_PRICEEVALUATIONREQUEST.fields_by_name['historicalPrices'].message_type = _PRICE
DESCRIPTOR.message_types_by_name['Price'] = _PRICE
DESCRIPTOR.message_types_by_name['PriceEvaluationRequest'] = _PRICEEVALUATIONREQUEST
DESCRIPTOR.message_types_by_name['PriceEvaluationResponse'] = _PRICEEVALUATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Price = _reflection.GeneratedProtocolMessageType('Price', (_message.Message,), {
  'DESCRIPTOR' : _PRICE,
  '__module__' : 'bolpy.proto.bol_pb2'
  # @@protoc_insertion_point(class_scope:bolproto.Price)
  })
_sym_db.RegisterMessage(Price)

PriceEvaluationRequest = _reflection.GeneratedProtocolMessageType('PriceEvaluationRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRICEEVALUATIONREQUEST,
  '__module__' : 'bolpy.proto.bol_pb2'
  # @@protoc_insertion_point(class_scope:bolproto.PriceEvaluationRequest)
  })
_sym_db.RegisterMessage(PriceEvaluationRequest)

PriceEvaluationResponse = _reflection.GeneratedProtocolMessageType('PriceEvaluationResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRICEEVALUATIONRESPONSE,
  '__module__' : 'bolpy.proto.bol_pb2'
  # @@protoc_insertion_point(class_scope:bolproto.PriceEvaluationResponse)
  })
_sym_db.RegisterMessage(PriceEvaluationResponse)



_PRICEEVALUATOR = _descriptor.ServiceDescriptor(
  name='PriceEvaluator',
  full_name='bolproto.PriceEvaluator',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=229,
  serialized_end=333,
  methods=[
  _descriptor.MethodDescriptor(
    name='EvaluatePrice',
    full_name='bolproto.PriceEvaluator.EvaluatePrice',
    index=0,
    containing_service=None,
    input_type=_PRICEEVALUATIONREQUEST,
    output_type=_PRICEEVALUATIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRICEEVALUATOR)

DESCRIPTOR.services_by_name['PriceEvaluator'] = _PRICEEVALUATOR

# @@protoc_insertion_point(module_scope)
