# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from bolpy.proto import bol_pb2 as bolpy_dot_proto_dot_bol__pb2


class PriceEvaluatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.EvaluatePrice = channel.unary_unary(
        '/bolproto.PriceEvaluator/EvaluatePrice',
        request_serializer=bolpy_dot_proto_dot_bol__pb2.PriceEvaluationRequest.SerializeToString,
        response_deserializer=bolpy_dot_proto_dot_bol__pb2.PriceEvaluationResponse.FromString,
        )


class PriceEvaluatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def EvaluatePrice(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PriceEvaluatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'EvaluatePrice': grpc.unary_unary_rpc_method_handler(
          servicer.EvaluatePrice,
          request_deserializer=bolpy_dot_proto_dot_bol__pb2.PriceEvaluationRequest.FromString,
          response_serializer=bolpy_dot_proto_dot_bol__pb2.PriceEvaluationResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'bolproto.PriceEvaluator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
